name: Java CI with Gradle

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Install Google Chrome
        run:   |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh

      - name: Run Cucumber tests
        run: gradle test -Dcucumber.options="--tags @TradMe"

      - name: Upload Cucumber report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cucumber report
          path: test-output/HtmlReport
